### ISSUE TITLE
Capture the Point

### ISSUE THREAD

**Issue by Regnak85** [taoneill/war#563]
Is there a possibility to add the feature to get points by capture points on the map?

Because, i've got a map, with 3 Towers. The Players should go to the tower and catch them with a woolblock or while they standing near to them. When they take a tower they get points. 
Eventually all 10 seconds 1 point per Tower.

Or something like the Arathi Bassin in World of Warcraft or so?

Would be really nice !

**Comment by cmastudios** [comment]
Added with most of this behavior!
