### ISSUE TITLE
War 1.9 SNAPSHOT not working with latest version of TagAPI

### ISSUE THREAD

**Issue by killyouslow** [taoneill/war#818]
War 1.9 doesnt work with TagApi for Minecraft 1.7.10 - players get disconnected from server do to java.lang.nullpointerexception when ever they enter a warzone to play a game, ive narrowed down the problem and found that War 1.9 doesnt support TagApi lastest build for minecraft 1.7.10

is there a recommened TagApi version that i should use for War 1.9?

**Comment by Niall7459** [comment]
@cmastudios Ive seen integration with HolographicDisplays on some servers, do you know how its done?

**Comment by DutcherGames** [comment]
:( it doesn't work on 1.9 can you pleeeaassee update it :) I had this plugin a couple of years ago on my 1.6 (i think) server and i like it :)
