### ISSUE TITLE
fall damage

### ISSUE THREAD

**Issue by 43Rockstarr** [taoneill/war#822]
Hello,

If you fall in a warzone from a high spot, you don't lose fall damage. PVP works, so I'm not sure why it would be doing this. Everyone has god off and is in survival. I have WorldGuard, is there a flag I should be setting or is it something in the war/zone config? Thank you!

**Comment by kugick** [comment]
Any plugins list?

**Comment by 43Rockstarr** [comment]
CoreProtect, HideAll, WorldEdit, War, Essentials, RemoteToolkitPlugin, GroupManager, ClearLag, BungeeTeleporter, Announcer, Janus, Votifier, ArcadeTokens, BanManager, Multiverse-Core, ProtocolLib, WorldGuard, AutoSaveWorld, NoCheatPlus, BungeePortals, ChatDisabled, EssentialsChat, SimpleHelpTickets, CustomJoinItems, GAListener, Vault, HideStream, EssentialsSpawn, EnjinMinecraftPlugin, CustomTab, uSkyBlock, TNTRun, HolographicDisplays, SkyWars, Citizens
