### ISSUE TITLE
Explosion error

### ISSUE THREAD

**Issue by bulldog731** [taoneill/war#823]
I installed crack shot in my server so that player can play war game.
Crack shot allow me to add explosion effect on guns and i can control the damage of explosion.
The explosion damage in warzone is different from the explosion damage out of warzone.
The explosion in warzone always kill player with one single explosion no matter how low the explosion damage is.
Sorry for my poor English, hope you can solve my problem.

**Comment by kugick** [comment]
Try to put realdeaths to true in the war.yml

**Comment by bulldog731** [comment]
Thank you for your anwser,but it don't work
