### ISSUE TITLE
Skulls reset problem.

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [taoneill/war#824]
http://pastebin.com/BYzpz9G3
Using this build
http://dev.bukkit.org/bukkit-plugins/war/?comment=1061

**Comment by kugick** [comment]
There is a problem with some skulls. Just look the coordinate in the logs and try to remove and replace thems.

**Comment by TheOnlyRealTGS** [comment]
Okay, I'll try that. Notice that it didn't happen on the previous build.

**Comment by kugick** [comment]
And I forgot to say that you have to save the zone again after.

**Comment by kugick** [comment]
Is everything working well now?

**Comment by TheOnlyRealTGS** [comment]
I don't have the time to do it sorry.

2015-05-09 16:22 GMT+02:00 kugick <notifications@github.com>:

**Comment by TheOnlyRealTGS** [comment]
Okay I teleported to the coordinates shown in the error, and it's not even inside the warzone. There is nothing in those cords.

**Comment by kugick** [comment]
Are you in the right world ? I'll try to help you when i'm gonna be back from Greece.

**Comment by TheOnlyRealTGS** [comment]
Yes.

**Comment by TheOnlyRealTGS** [comment]
I replaced all skulls I could find with new ones, and the error disappeared.
New bug though: It doesn't save all data for the skulls, I spawned the skull with this command:
```/give @p skull 1 3 {display:{Name:"Skull"},SkullOwner:{Id:"c659cdd4-e436-4977-a6a7-d5518ebecfbb",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWFlMzg1NWY5NTJjZDRhMDNjMTQ4YTk0NmUzZjgxMmE1OTU1YWQzNWNiY2I1MjYyN2VhNGFjZDQ3ZDMwODEifX19"}]}}}```

**Comment by kugick** [comment]
Oh its more clear now. The skulls you are using who have a command like this one are custom skulls coming from another server than the Mojang server. It is not supported atm. But I will note it if I can get this working on next version of War.

**Comment by TheOnlyRealTGS** [comment]
Yeah well, I'm not sure what it was in the past, but I wanted some cool skulls when I replaced the old ones.
