### ISSUE TITLE
Loadout kit permissions?

### ISSUE THREAD

**Issue by 43Rockstarr** [taoneill/war#825]
Hi,

What are the permissions to use created loadout kits? If someone could help me with this I'd really appreciate it! I can't figure it out and can't find it anywhere. Thank you!

~43Rockstarr

**Comment by kugick** [comment]
There is a list of all permissions from plugin.yml inside of the .jar file. I don't remember, but I think there is no permission for loadout. You simply sneak in your spawn then the kit change. If I am right, it could be great feature to add in War 2.0.

permissions:
  war.*:
    description: Full War permissions. Create and destroy warzones. Change War configuration.
    default: op
    children:
      war.admin: true
      war.zonemaker: true
      war.player: true
      war.warp: true
      war.build: true
      war.pvp: true
  war.admin:
    description: War admin rights. Create and destroy warzones. Change War configuration.
    default: false
    children:
      war.zonemaker: true
      war.player: true
      war.build: true
  war.zonemaker:
    description: Warzone maker rights. Create and edit warzones, but you can only edit a warzone if you are its author.
    default: false
    children:
      war.player: true
      war.build: true
  war.player:
    description: Lets you participate in War matches.
    default: true
  war.warp:
    description: Gives you access the /zone and /warhub commands that let you teleport to all warzones.
    default: true
  war.build:
    description: 
      Useful only after using /warcfg buildinzonesonly:true. This node circumvents the build restriction and lets you build outside warzones. 
      Give war.build to people that you consider worthy of having build rights. 
    default: false
  war.pvp:
    description: 
      Useful only after using /warcfg pvpinzonesonly:true. This node circumvents the pvp restriction and lets you pvp outside warzones. 
      To setup a pvp world, give war.pvp to players, but only as a permission specific to the pvp world. Other worlds will remain protected
      by the pvpinzonesonly setting. NOTE - No matter what, pvp must be turned on in your server.properties file, otherwise War won't work.
    default: false

**Comment by 43Rockstarr** [comment]
I actually just discovered there is a way to set a permission for each kit. Above the slots option for each kit in the war.yml (and for each arena.yml), you can type permission: yourpermission.here and it creates a permission which you then can add to each group/rank. This worked for me and this can now be marked as solved.
