### ISSUE TITLE
"truce"

### ISSUE THREAD

**Issue by gabedrayton** [taoneill/war#830]
The plugin won't let some people from opposing teams fight because they're in a "truce" as the War plugin says, its quite frusterating, please help!

**Comment by kugick** [comment]
"Truce" ?

**Comment by Tommsy64** [comment]
Are you sure this isn't happening because of a factions plugin?

**Comment by cmastudios** [comment]
You have factions installed? That would be precisely why then. In the meantime you might try to add another world to your server, disable factions there, and set up your war zones there.

**Comment by gabedrayton** [comment]
Ohh! Ok! Thanks so much for your help! I was confused on why it was doing that! Thanks!

**Comment by gabedrayton** [comment]
It didn't work 100%- it's letting opponents hit me but not letting me hit them. I uninstalled the Factions plugin.

**Comment by Tommsy64** [comment]
Provide a list of plugins currently installed.

**Comment by gabedrayton** [comment]
Hello??

**Comment by dylanhansch** [comment]
As @Tommsy64 said, you should provide a list of installed plugins. It'll help 'us' diagnose the issue better. This isn't a feature of War, so it's likely another plugin interfering.

**Comment by gabedrayton** [comment]
Ok! I sent a photo but maybe it didn't get delivered. 
The plugins we use are: Worldedit, Support, Installer, Justonemore, War, Essentials, FeatherEconomy, Groupmanager, Chatcontrol, Buycraft, Ranklist, Buycraftannouncer, AdvancedBan, SpawnJoin, Headsplus, PermColorSigns, WorldGuard, Multiverse-Core, Protocollib, TheWalls, Buycraftextracommands, Kitbattle, ShopKeepers, Hovermessage, Essentialsprotect, Antiplugincommand, Essentialsantibuild, CobraKits, AdvancedMOTD, Multiverse-portals, Playercountmessage, Tablist, Vault, EssentialsSpawn, ChatColor, Actionbar, MassiveCore, Titlebar, Admin-chat-channel, Minigames, Project-HungerGames, WarpPortals, Customscoreboard.

-Gabbay

**Comment by gabedrayton** [comment]
Hello?

**Comment by kugick** [comment]
PvP can be disabeld by Vanilla scoreboard, Vanilla gamerule, WorldGuard,
Essentials and Multiverse-Core. Give it a look.

2015-11-14 13:01 GMT-05:00 gabedrayton <notifications@github.com>:

> Hello?
>
> Sent from my iPhone
>
> > On Nov 12, 2015, at 7:00 PM, Gabriel Drayton (Gabe) <
> gabe.drayton10@gmail.com> wrote:
> >
> > Ok! I sent a photo but maybe it didn't get delivered.
> > The plugins we use are: Worldedit, Support, Installer, Justonemore, War,
> Essentials, FeatherEconomy, Groupmanager, Chatcontrol, Buycraft, Ranklist,
> Buycraftannouncer, AdvancedBan, SpawnJoin, Headsplus, PermColorSigns,
> WorldGuard, Multiverse-Core, Protocollib, TheWalls, Buycraftextracommands,
> Kitbattle, ShopKeepers, Hovermessage, Essentialsprotect, Antiplugincommand,
> Essentialsantibuild, CobraKits, AdvancedMOTD, Multiverse-portals,
> Playercountmessage, Tablist, Vault, EssentialsSpawn, ChatColor, Actionbar,
> MassiveCore, Titlebar, Admin-chat-channel, Minigames, Project-HungerGames,
> WarpPortals, Customscoreboard.
> >
> > -Gabbay
> >
> > Sent from my iPhone
> >
> >> On Nov 12, 2015, at 4:52 PM, Dylan Hansch <notifications@github.com>
> wrote:
> >>
> >> As @Tommsy64 said, you should provide a list of installed plugins.
> It'll help 'us' diagnose the issue better. This isn't a feature of War, so
> it's likely another plugin interfering.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub.
> >>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taoneill/war/issues/830#issuecomment-156728623>.
>



-- 
kugick <http://kugick.net> (Samuel Collin)

**Comment by gabedrayton** [comment]
I think it's Essentials that's making it so people can't PVP- I tried temporarily disabling Essentials, and it let us PVP. When turned it back on it didn't work. I tried to find if any rank had the essentials.pvp.protect permission node (idk if it was exactly that permission node) and I couldn't find any. Where should I go check under essentials?

**Comment by kugick** [comment]
There is a section for some events (like falling/fire.. damages) and PvP. We can't config for you Essentials. And just saying that I think this permission node isn't working.

Envoyé de mon iPod

**Comment by gabedrayton** [comment]
Hello?!?

**Comment by Tommsy64** [comment]
@gabedrayton Try disabling EssentialsProtect as this will remove the protection features from Essentials.

**Comment by gabedrayton** [comment]
Ok!!! Thanks to everyone solved the issue, It was Essentialsprotect.
