### ISSUE TITLE
how to turn off protection in lobby and hub?

### ISSUE THREAD

**Issue by redstoneengie** [taoneill/war#836]
hi is there a way u can turn off portection in lobby and hub? because when i wanna build in the hub it says  
You Can't build here. how do u turn it off?

**Comment by dylanhansch** [comment]
At the moment I don't think there's any config option to turn off protection. Try building a replica of the lobby in a different location then adding all the builds you wanted inside. Then go and set your lobby so it matches up with the replica you made. Then if you ever need to edit the builds just move the lobby out, make your changes, and move the lobby back in.

**Comment by redstoneengie** [comment]
oh ok thats fine

**Comment by cmastudios** [comment]
Check the guide I just created for information! https://cmastudios.me/war/lobby-customization/
