### ISSUE TITLE
Saving loadouts in 1.11.2 duplicates items

### ISSUE THREAD

**Issue by MilosBulat** [taoneill/war#839]
Saving an equipped loadout duplicates equipped items in inventory.

**Comment by kugick** [comment]
Not sure if this is a bug, were you able to do this in previous server (Bukkit) version?

**Comment by MilosBulat** [comment]
I didn't try it tbh. It worked a long time ago when i tested your War
plugin on 1.4.

Server is :
Spigot 1.11.2

Maybe its just a compatibility issue.

**Comment by cmastudios** [comment]
I will try to test and fix these issues this weekend as available. Thanks for the reporting and your interest in War!

**Comment by cmastudios** [comment]
Should be fixed in the following build: http://ftp.cmastudios.me/maven/com/tommytony/war/1.10-SNAPSHOT/war-1.10-20170716.235628-3.jar
