### ISSUE TITLE
MC 1.8 Version of War?

### ISSUE THREAD

**Issue by PrinceOfIonia** [taoneill/war#841]
Well, I can't find it, the guy said you could download it in the dev builds (http://ci.tommytony.com/job/War/com.tommytony$war/), but the website is down and I can't find another download link, can someone help? Maybe they have an older 1.8 Verion or something, but I don't care, anything will do as long as it runs on a Minecraft 1.8 Bukkit/Spigot Server. Thanks!

**Comment by cmastudios** [comment]
Attached please find a version of the plugin compiled against Bukkit 1.8. This should work for your needs. If not, please let me know. Thanks!
[war-1.10-SNAPSHOT.jar.zip](https://github.com/taoneill/war/files/1150642/war-1.10-SNAPSHOT.jar.zip)

**Comment by PrinceOfIonia** [comment]
It seems to have worked! Thank you so much! Maybe you could post this somewhere for other people, because it appears that the snapshot website is down.
