### ISSUE TITLE
don't work on 1.13

### ISSUE THREAD

**Issue by maateh** [taoneill/war#844]
please fix the war resetzone, error in 1.13 version:

---------------------------

16:17:03 [WARN] [War] Task #4462 for War v1.9 generated an exception
16:17:03 java.lang.IllegalArgumentException: Provided data is not of type org.bukkit.material.WoodenStep, found org.bukkit.material.Wood
16:17:03 at org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockState.setData(CraftBlockState.java:113) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:17:03 at com.tommytony.war.mapper.ZoneVolumeMapper.load(ZoneVolumeMapper.java:141) ~[?:?]
16:17:03 at com.tommytony.war.volume.ZoneVolume.resetSection(ZoneVolume.java:85) ~[?:?]
16:17:03 at com.tommytony.war.job.PartialZoneResetJob.run(PartialZoneResetJob.java:104) ~[?:?]
16:17:03 at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:17:03 at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:17:03 at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:17:03 at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:17:03 at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:17:03 at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:17:03 at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by cmastudios** [comment]
Fixed
