### ISSUE TITLE
Size for custom inventory must be a multiple of 9 and 54 slots (got 63) #858 

### ISSUE THREAD

**Issue by JacksonWillford** [taoneill/war#859]
Good morning,

Server version: Spigot 1.16.4

After running a new install of your plugin using your 2.0.0 release branch #858 , I noticed that after clicking the "Manage War" option, there is a stack trace saying that the chestUI being built is too large to be handled.
https://i.imgur.com/opnJP9V.png

After looking, I found the issue in WarAdminUI.java in getSize() was returning 9 * 7.

After changing that to be 9 * 6 (maximum size supported), I am now getting an ArrayIndexOutOfBoundsException due to there being too many items trying to be added to the ChestUI.

**Comment by cmastudios** [comment]
Can confirm the new size limitation is causing an issue. I'm going to try moving the warzone default config out of the main war config UI I think.

**Comment by cmastudios** [comment]
Here's my new UI proposal to solve the issue:
![image](https://user-images.githubusercontent.com/1058735/100256640-a20ef600-2f0a-11eb-86a7-542648adf2fd.png)

**Comment by cmastudios** [comment]
Fixed in the latest 2.0.0-RC6 available at http://maven.cmastudios.me/wardevbuilds/devbuilds.html. Please let me know if you run into more issues with the 1.16 support! I don't have a server anymore so hard to test multiplayer features.
