### ISSUE TITLE
java.lang.NoSuchMethodError when creating a warzone

### ISSUE THREAD

**Issue by JacksonWillford** [taoneill/war#860]
Using War v2.0.0-RC6-SNAPSHOT
Version: 1.16 Spigot server

Steps to reproduce:
1. Make a worldedit selection
2. In the war UI, select "Create Warzone"
3. Type a name for the warzone

Stacktrace: https://i.imgur.com/wr1q9Yo.png

I can't seem to get the pom to recognize the new version of WorldEdit, I tried to get Worldedit v7.1.0 to be a dependency, but my environment is being a little funny.

**Comment by cmastudios** [comment]
I last tested against WorldEdit v7.1.0, I presume this error is only with 7.2.0?

**Comment by cmastudios** [comment]
Cannot reproduce with WorldEdit v7.2.0 and War 2.0.0-RC6. 
Are you using the official War builds from http://maven.cmastudios.me/wardevbuilds/devbuilds.html ?

**Comment by JacksonWillford** [comment]
Let me try with 7.2.0

**Comment by JacksonWillford** [comment]
Really weird, that seemed to have worked. I was cloning the project and building it myself. Are there any changes on your end that I should have made?

**Comment by cmastudios** [comment]
Interesting. All I did was run `mvn package` and then used the `war-2.0.0-RC6-SNAPSHOT.jar` file (NOT the -shaded or -original). Using JDK 14. Let me know if you discover anything else on this.
